# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
NaroBody_1_NaroBody_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: NaroBody_1_NaroBody_2_joint
  pid: {p: 10.0, i: 1.0, d: 0.0}
