# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
front_left_wheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_wheel_joint
  pid: {p: 10.0, i: 1.0, d: 0.0}
  
front_right_wheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_wheel_joint
  pid: {p: 10.0, i: 1.0, d: 0.0}
  
rear_left_wheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_left_wheel_joint
  pid: {p: 10.0, i: 1.0, d: 0.0}
  
rear_right_wheel_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_right_wheel_joint
  pid: {p: 10.0, i: 1.0, d: 0.0}